### PR TITLE
Feature/double speck reader

### PR DESCRIPTION
**Pull request by buzinsky**
Seems to work, in that it is printing out the correct high power bins, producing sensible track segments

Download data from this DAQ test: https://docs.google.com/document/d/1tSXIeRM3BcXMRS208RdlFI2aivg6MCaBS7x4IsaZoJ0/edit#heading=h.v4krbduoceqm
We use

Noise baseline: RID 1109 **(acq = 1)**
Spec (Vaunix On): RID 1114 (acq = 0)
Speck (Vaunix On): RID 1117 (acq = 0)
(Filenames are already set, just make them available)

Both vaunix runs are at 10^10 slope. Not sure if the DB scan radius is set correctly
For the zero-suppressed code, I needed to lower the threshold on the discriminator to see anything. Makes sense that it wouldn't necessarily be the same

My laptop crashes if I try to run the full second. Could just be a local issue. 

Memory requirements should be ~2x bigger than before
Sometimes I just have to call the Katydid command twice for it to "do" anything. Hoping it is just my local machine + config settings that are needed to finalize this

Configs are attached

[configs.zip](https://github.com/Helium6CRES/katydid/files/14390960/configs.zip)

### CODE REVIEW

**Comment by harringtonh** [comment]
Looks like it's mostly working! Amazing!

**spec:**
Packet number seems to be working. 
image
as is slice
image
but something goes wrong with TimeInRunC when I try to do a full second
image
I also get lots of bins passing the threshold at the top.
image
I can work on the spline as that if definitely the cause of the excess of pints passing at the top. 
image
Noise looks good.
For debugging until I fix the spline, I would drop STF. Then you should be able to run a full second.

**speck:**
"For the zero-suppressed code, I needed to lower the threshold on the discriminator to see anything. " I don't follow. For me it works fine with snr-threshold-power: 9.0 and logically I think that should work. Any lower and you will see the same thing as snr-threshold-power: 9.0, any higher will start to cut if zero-suppression was done at SNR=9 (edit. It looks like zero-supression used a lower value than 9 is that right?)
Has the same issue with TimeInRunC
image

Notes:
How are you doing the fit for receiver zero-supression? The high-density of points over threshold in this data means those also passed the zero-supression. Are you also using a spline with the same parameters?
image
For both I'm curious how long they take relative to the single channel version, maybe just to the discriminatory and writing. I have not timed them yet, but wonder if it's twice as long or more. Worth knowing.

I did not test the Trap Off implementation.

**Comment by buzinsky** [comment]
`something goes wrong with TimeInRunC when I try to do a full second`
I will look at this tomorrow. Not clear why this would happen

`edit. It looks like zero-supression used a lower value than 9 is that right?` Yes the default is 7, so that we have a bit of wiggle room. Still greatly reduces the file size

`I don't follow. For me it works fine with snr-threshold-power: 9.0 and logically I think that should work. ` I thought the discriminator calculation would be different and the thresholds would not correspond between zero-suppressed data vs. uncompressed data near all that near zero noise. Didn't look closely & I could have been hasty with this statement. 

` How are you doing the fit for receiver zero-supression? The high-density of points over threshold in this data means those also passed the zero-supression. Are you also using a spline with the same parameters?` No spline. It just an average over the raw noise files over a full second. The threshold is then some factor times that (right now 7). This factor (and the noise file names) go in the database. If we want something that behaves better at these high frequencies, we may want to store the full 8192 array in the database (or somewhere)? Not sure.

` For both I'm curious how long they take relative to the single channel version, maybe just to the discriminatory and writing. I have not timed them yet, but wonder if it's twice as long or more. Worth knowing.` True, good point, didn't check. 2x is a good guess. If anything, this should be slightly under 2x longer, as overhead is not doubled. I think the fair test is to do 2 copies of e.g. the lower half of the spectrogram, instead of upper + lower. Upper has many more points, so it will (unfairly) make it look much slower than the code is. On the other hand, events that can go between the lower and upper spectrograms means the STF should be slower than the sum of the individual halves 

`I did not test the Trap Off implementation.` Sure, we probably need slewing data in some form. This could be something that is not merged by the time we take data, if this is the only sticking point

Thanks Heather. Will update later

**Comment by buzinsky** [comment]
Both these issues should be fixed. I figured out the cause of the segfaults I was getting on my machine when the number of slices was too large.

My crashes were caused by the array pkt_num[fNSpectra], which stores the packet numbers of each packet
In C++, arrays are stored on the stack, vectors are stored on the heap. The stack is faster, though memory limited to a few MB, and can easily crash if too much is put on them. This would be why it works on some machines and not others. I changed this in LongSpecProcessor too, which just changes the internal details of how that data is stored, and not any operations on it. This should make the code more stable 

Finally, the issue with the negative TimeInRunC's was a result of overflowing the maximum integers. ints are 4 bytes, with a maximum value of 2147483647. It turned out that the product `i*fFreqBins*fROACH_FFT_Avg` did exceed this value (i < 146484, fFreqBins = 8192, fROACH = 2 gives 2.4e9). I moved the `/fFreqMax` up to the start of the line to convert to a double. One could convert to long ints then to doubles. I added a comment about this as it was not something I was thinking about

The timing didn't quite make sense to me. It was actually faster for .specks with upper and lower than just lower? Didn't look more into it, as it isn't an issue in itself. .spec's behave normally. The difference is just a few seconds

Screenshot 2024-02-26 at 12 13 57 PM

**Comment by harringtonh** [comment]
All sounds good to me for a merge then!

**Pull request merged**
